### ISSUE TITLE
Checklist of Criteria - Category 9: Presentation and questions

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-3#10]
### Category 9 - Presentation and questions
- [x] The web application is presented and a demo is made as you would do it to a colleague/another team/boss/client/investor so they can understand what you created, why and how
- [x] The presentation is clear and well prepared - everyone speaks during the presentation
- [x] The answers to the questions are correct
