### ISSUE TITLE
Checklist of Criteria - Category 3: Docker and Docker Compose

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-3#4]
### Category 3 - Docker and Docker Compose
- [x] The network application is packaged and published to GitHub Container Registry with Docker so other people can use your network application with Docker
- [x] The README describes **explicit commands** to build and publish your network application with Docker
- [ ] The README describes **explicit commands** to use your network application with Docker Compose so other people can easily use it
- [x] The Docker applications (Traefik and your web application) are split into multiple directories and make usage of networks to communicate together

**Comment by maellemelody** [comment]
For some reason, this wasn't closed. Manually doing it.
