### ISSUE TITLE
Checklist of Criteria - Category 6: HTTP and curl

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-3#7]
### Category 6 - HTTP and curl
- [x] The README (or repository) contains the application protocol interface (API) that describes the web application
- [x] The web application makes usage of at least the following HTTP methods: `GET`, `POST`, `PATCH`/`PUT` and `DELETE`
- [x] The web application return status codes must be consistent and reflect the HTTP methods
- [x] The web application offers at least two resources (= domains) on which to operate CRUD operations
- [x] The README explains how to use your web application with **explicit examples using curl** with outputs to demonstrate how to interact with your web application **deployed on the Internet**
