### ISSUE TITLE
Checklist of Criteria - Category 7: Web infrastructures

### ISSUE THREAD

**Issue by maellemelody** [Dylan-Langumier/DAI-Practical-Work-3#8]
### Category 7 - Web infrastructures
- [x] The README (or repository) contains instructions how to install and configure the virtual machine with each step
- [x] The README (or repository) contains explains how to configure the DNS zone to access your web application
- [x] The README (or repository) contains instructions how to deploy, run and access the web applications with Docker Compose
- [x] At least Traefik and your web application are deployed on the virtual machine
- [x] The README displays the domain names configuration in the DNS zone to validate everything is set up right
- [x] The web applications (the Traefik dashboard and your own application) are accessible using a domain name and/or subdomain names
- [x] The web applications (the Traefik dashboard and your own application) use automatic HTTPS/TLS certificate generations with Let's Encrypt

**Comment by maellemelody** [comment]
For some reason, this wasn't closed. Manually doing it.
